
# Site settings
title: Think and Do it    				  	#你博客的标题
SEOTitle: Think and Do it    	 #显示在浏览器上搜索的时候显示的标题
header-img: img/post-bg-rwd.jpg  	#显示在首页的背景图片
email: fan.lin.nj@gmail.com	
description: "Think and Do it"  			 #网站介绍
keyword: "Think and Do it" #关键词
url: "https://lion991.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写

# Sidebar settings
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description: "Think and Do it"
sidebar-avatar:/img/avatar-by.JPG      # 你的个人头像 这里你可以改成我在img文件夹中的两张备用照片 img/avatar-m 或 avatar-g
